# Generated by Django 5.0.6 on 2024-06-14 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFold',
            fields=[
                ('id_noteFold', models.IntegerField(db_column='idNoteFold', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'NoteFold',
                'verbose_name_plural': 'NoteFolds',
                'db_table': 'NoteFolds',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(db_column='idArchivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('origen', models.CharField(max_length=30, verbose_name='origen')),
                ('tipo', models.ForeignKey(db_column='idNoteFold', on_delete=django.db.models.deletion.DO_NOTHING, to='InterfazWeb.notefold', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'Archivos',
            },
        ),
    ]
